import React,{useMemo,useState} from 'react';import{Link}from'react-router-dom';import{RouteMeta}from'./RouteMeta';
type Q={id:string;dimension:string;label:string;hint:string;options:{value:number;text:string}[]};
const scale=(texts:string[])=>texts.map((text,i)=>({value:i+1,text}));
const questions:Q[]=[
{id:'usecase',dimension:'Zielklarheit',label:'Wie klar ist der erste Anwendungsfall beschrieben?',hint:'Ein guter Use Case benennt Nutzer, Auslöser, Arbeitsschritte und gewünschtes Ergebnis.',options:scale(['Noch keine Idee','Ein grober Themenbereich','Ein Prozess ist benannt','Ablauf und Ziel sind beschrieben','Ablauf, Ziel und Messgröße sind klar'])},
{id:'process',dimension:'Prozess',label:'Wie stabil läuft der heutige Prozess?',hint:'KI verstärkt häufig auch Unklarheiten im bestehenden Ablauf.',options:scale(['Stark personenabhängig und unklar','Viele Ausnahmen, kaum dokumentiert','Kernablauf ist bekannt','Dokumentiert mit klaren Übergaben','Dokumentiert, gemessen und verantwortlich zugeordnet'])},
{id:'data',dimension:'Daten',label:'Wie zugänglich sind die benötigten Informationen?',hint:'Zum Beispiel Dokumente, Wissensartikel, CRM-Felder oder historische Fälle.',options:scale(['Unbekannt oder nicht digital','Verteilt in Postfächern/Ordnern','Digital, aber uneinheitlich','Zentral und überwiegend gepflegt','Zentral, gepflegt und mit Zugriffsregeln'])},
{id:'systems',dimension:'Technik',label:'Wie gut lassen sich Ihre Systeme anbinden?',hint:'Bewerten Sie Exporte, APIs, Rollen und verfügbare technische Betreuung.',options:scale(['Noch nicht geprüft','Nur manuelle Übertragung bekannt','Exporte sind möglich','Wichtige Systeme bieten Schnittstellen','Schnittstellen, Testzugang und Betreuung sind verfügbar'])},
{id:'risk',dimension:'Governance',label:'Wie sind Qualität, Datenschutz und Freigaben organisiert?',hint:'Gemeint sind Verantwortliche und ein überprüfbarer Umgang mit Fehlern.',options:scale(['Noch niemand verantwortlich','Risiken sind bekannt, Regeln fehlen','Eine verantwortliche Person ist benannt','Regeln und menschliche Freigaben sind definiert','Regeln, Tests, Monitoring und Eskalation sind etabliert'])},
{id:'adoption',dimension:'Einführung',label:'Wie wird das Team in die Einführung einbezogen?',hint:'Akzeptanz entsteht durch Beteiligung, Training und sichtbares Feedback.',options:scale(['Noch nicht geplant','Information nach Fertigstellung','Einzelne Nutzer geben Feedback','Pilotgruppe und Training sind geplant','Pilotgruppe, Training und Erfolgskriterien sind vereinbart'])},
];
const nextSteps:Record<string,string>={Zielklarheit:'Einen Prozess in Auslöser, Schritte, Ergebnis und Messgröße zerlegen.',Prozess:'Den Ist-Ablauf mit Ausnahmen und Verantwortlichen auf einer Seite dokumentieren.',Daten:'Für zehn echte Fälle Datenquellen, Qualität und Zugriffsrechte prüfen.',Technik:'Export- und API-Möglichkeiten des wichtigsten Systems mit der IT klären.',Governance:'Menschliche Freigabe, Fehlerfall und zulässige Daten schriftlich festlegen.',Einführung:'Eine kleine Pilotgruppe und einen festen Feedbacktermin bestimmen.'};
export const KIAudit:React.FC=()=>{const[index,setIndex]=useState(0),[answers,setAnswers]=useState<Record<string,number>>({}),[done,setDone]=useState(false);const q=questions[index];const dimensions=useMemo(()=>questions.map(x=>({name:x.dimension,value:answers[x.id]||0})),[answers]);const avg=dimensions.reduce((s,x)=>s+x.value,0)/questions.length;const label=avg<2.4?'Erst fokussieren':avg<3.7?'Pilot vorbereiten':'Pilot strukturiert starten';const weak=[...dimensions].sort((a,b)=>a.value-b.value).slice(0,3);
const select=(value:number)=>{setAnswers(a=>({...a,[q.id]:value}));if(index<questions.length-1)setTimeout(()=>setIndex(i=>i+1),120);else setTimeout(()=>setDone(true),120)};const restart=()=>{setIndex(0);setAnswers({});setDone(false)};
if(done)return <main className="min-h-screen bg-base pt-32 pb-24 px-4 sm:px-6"><RouteMeta title="KI-Ausgangslage | Ainzigartig" description="Sechs Dimensionen für einen belastbaren ersten KI-Pilot."/><div className="max-w-[900px] mx-auto"><header className="text-center max-w-2xl mx-auto mb-10"><p className="text-xs uppercase tracking-[.14em] text-light mb-3">Ihre Orientierung</p><h1 className="font-editorial text-4xl md:text-6xl">{label}</h1><p className="text-sm text-muted mt-4">Kein wissenschaftlicher Benchmark und kein Vergleich mit anderen Unternehmen, sondern eine strukturierte Auswertung Ihrer Selbsteinschätzung.</p></header><div className="grid md:grid-cols-2 gap-6"><section className="brand-card bg-surface p-6 md:p-8"><h2 className="font-editorial text-2xl mb-6">Sechs Voraussetzungen</h2><div className="space-y-5">{dimensions.map(d=><div key={d.name}><div className="flex justify-between text-sm mb-2"><span>{d.name}</span><span>{d.value}/5</span></div><div className="h-2 bg-ink/10 rounded-full"><div className="h-full bg-accent rounded-full" style={{width:`${d.value*20}%`}}/></div></div>)}</div></section><section className="brand-card bg-[#F3EFEA] p-6 md:p-8"><p className="text-xs uppercase tracking-[.14em] text-light mb-4">Die drei sinnvollsten nächsten Schritte</p><ol className="space-y-5">{weak.map((d,i)=><li key={d.name} className="flex gap-4"><span className="font-editorial text-3xl text-accent-hover">{i+1}</span><div><strong className="text-sm">{d.name}</strong><p className="text-sm text-muted mt-1 leading-relaxed">{nextSteps[d.name]}</p></div></li>)}</ol></section></div><div className="mt-6 brand-card bg-surface p-6"><h2 className="font-editorial text-xl">Was das Ergebnis nicht sagt</h2><p className="text-sm text-muted mt-2 leading-relaxed">Es bewertet weder rechtliche Konformität noch Wirtschaftlichkeit oder Modellqualität. Dafür braucht es einen konkreten Prozess, echte Beispieldaten und einen begrenzten Test mit definierten Abbruchkriterien.</p></div><div className="flex flex-col sm:flex-row justify-center gap-3 mt-8"><Link to="/#kontakt" className="brand-pill justify-center bg-ink text-white">Pilot einordnen lassen</Link><button onClick={restart} className="brand-pill justify-center bg-surface">Neu starten</button></div></div></main>;
return <main className="min-h-screen bg-base pt-32 pb-24 px-4 sm:px-6"><RouteMeta title="KI-Ausgangslage | Ainzigartig" description="Sechs praxisnahe Fragen zur Ausgangslage für einen KI-Pilot."/><div className="max-w-[760px] mx-auto"><header className="text-center mb-10"><p className="text-xs uppercase tracking-[.14em] text-light mb-3">KI-Ausgangslage</p><h1 className="font-editorial text-[clamp(2.5rem,6vw,4rem)] leading-tight">Ist Ihr nächster KI-Pilot gut vorbereitet?</h1><p className="text-sm md:text-base text-muted mt-4">Sechs Voraussetzungen statt eines pauschalen „Reifegrad“-Versprechens.</p></header><section className="brand-card bg-surface p-6 md:p-9"><div className="flex justify-between text-xs text-light mb-2"><span>Frage {index+1} von {questions.length}</span><span>{Math.round(((index+1)/questions.length)*100)}%</span></div><div className="h-1.5 bg-ink/10 rounded-full mb-9"><div className="h-full bg-accent rounded-full transition-all" style={{width:`${((index+1)/questions.length)*100}%`}}/></div><p className="text-xs uppercase tracking-[.12em] text-accent-hover font-semibold mb-2">{q.dimension}</p><h2 className="font-editorial text-2xl md:text-3xl leading-tight">{q.label}</h2><p className="text-sm text-light mt-2 mb-7">{q.hint}</p><div className="space-y-2.5">{q.options.map(o=><button key={o.value} onClick={()=>select(o.value)} className={`w-full text-left p-4 rounded-2xl border text-sm focus:outline-none focus:ring-2 focus:ring-accent ${answers[q.id]===o.value?'border-accent bg-accent/15':'border-ink/10 bg-base/50 hover:border-ink/30'}`}>{o.text}</button>)}</div>{index>0&&<button onClick={()=>setIndex(i=>i-1)} className="mt-6 text-xs text-light hover:text-ink">← Zurück</button>}</section></div></main>};
