import React, { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { RouteMeta } from './RouteMeta';

const eur=(n:number)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);
const num=(n:number)=>new Intl.NumberFormat('de-DE',{maximumFractionDigits:0}).format(n);
interface FieldProps{label:string;value:number;set:(n:number)=>void;min:number;max:number;step?:number;suffix:string;hint:string}
const Field=({label,value,set,min,max,step=1,suffix,hint}:FieldProps)=><label className="block"><span className="block text-xs uppercase tracking-[.14em] text-muted mb-2">{label}</span><div className="flex items-baseline gap-2 border-b border-ink/20 focus-within:border-accent"><input type="number" inputMode="decimal" min={min} max={max} step={step} value={value} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n))set(Math.min(max,Math.max(min,n)))}} className="min-w-0 w-full bg-transparent py-2 text-3xl font-editorial focus:outline-none"/><span className="text-sm text-light whitespace-nowrap">{suffix}</span></div><span className="block text-xs text-light mt-2 leading-relaxed">{hint}</span></label>;

export const ROICalculator:React.FC=()=>{
  const [people,setPeople]=useState(5),[hours,setHours]=useState(6),[rate,setRate]=useState(55),[share,setShare]=useState(30),[adoption,setAdoption]=useState(70),[monthlyCost,setMonthlyCost]=useState(800),[setupCost,setSetupCost]=useState(6000);
  const result=useMemo(()=>{const baseline=people*hours*52;const recoverable=baseline*(share/100)*(adoption/100);const gross=recoverable*rate;const cost=setupCost+monthlyCost*12;const net=gross-cost;return{baseline,recoverable,gross,cost,net,months:gross>0?cost/(gross/12):Infinity}},[people,hours,rate,share,adoption,monthlyCost,setupCost]);
  const scenarios=[{name:'Vorsichtig',factor:.65},{name:'Ihre Annahme',factor:1},{name:'Günstig',factor:1.25}].map(s=>({...s,hours:result.recoverable*s.factor,net:result.gross*s.factor-result.cost}));
  return <main className="min-h-screen pt-32 pb-24 px-4 sm:px-6 bg-base text-ink"><RouteMeta title="ROI-Szenario | Ainzigartig" description="Ein transparenter Business-Case-Rechner mit editierbaren Annahmen."/><div className="max-w-[1120px] mx-auto"><header className="max-w-3xl mb-12"><p className="text-xs uppercase tracking-[.18em] text-muted mb-5">Business-Case-Werkbank</p><h1 className="font-editorial text-[clamp(2.5rem,6vw,4.5rem)] leading-[1.04]">Keine Benchmark-Magie.<br/><em>Ihre Annahmen.</em></h1><p className="text-base md:text-lg text-muted leading-relaxed mt-6 max-w-2xl">Modellieren Sie einen konkreten repetitiven Prozess. Jede Zahl ist editierbar; das Ergebnis ist ein Szenario, keine Einspargarantie.</p></header>
    <div className="grid lg:grid-cols-[1fr_.95fr] gap-8 lg:gap-14"><section className="brand-card bg-surface p-6 md:p-8" aria-labelledby="inputs"><h2 id="inputs" className="font-editorial text-2xl mb-2">1. Arbeitsaufwand</h2><p className="text-sm text-muted mb-8">Beginnen Sie mit einem einzelnen, klar abgrenzbaren Workflow.</p><div className="grid sm:grid-cols-2 gap-8"><Field label="Beteiligte Personen" value={people} set={setPeople} min={1} max={500} suffix="Personen" hint="Personen, die diesen Workflow regelmäßig bearbeiten."/><Field label="Aufwand je Person" value={hours} set={setHours} min={.5} max={40} step={.5} suffix="Std./Woche" hint="Nur Zeit für den betrachteten Workflow."/><Field label="Vollkostensatz" value={rate} set={setRate} min={10} max={300} suffix="€/Std." hint="Interner Satz inklusive sinnvoller Nebenkosten."/><Field label="Technisch reduzierbarer Anteil" value={share} set={setShare} min={0} max={100} suffix="%" hint="Anteil, der nach einem Prozesstest realistisch entfällt."/></div><h2 className="font-editorial text-2xl mt-12 mb-8">2. Einführung</h2><div className="grid sm:grid-cols-2 gap-8"><Field label="Tatsächliche Nutzung" value={adoption} set={setAdoption} min={0} max={100} suffix="%" hint="Berücksichtigt, dass ein Tool nicht sofort überall genutzt wird."/><Field label="Laufende Kosten" value={monthlyCost} set={setMonthlyCost} min={0} max={100000} step={100} suffix="€/Monat" hint="Software, Betrieb, Qualitätssicherung und Betreuung."/><Field label="Einmalige Einführung" value={setupCost} set={setSetupCost} min={0} max={500000} step={500} suffix="€" hint="Konzeption, Integration, Schulung und interne Zeit."/></div></section>
      <section className="lg:sticky lg:top-28 lg:self-start space-y-5" aria-live="polite"><div className="rounded-[28px] bg-ink text-white p-6 md:p-8"><p className="text-xs uppercase tracking-[.14em] text-white/55">Jahr 1 · Ihre Annahme</p><p className={`font-editorial text-[clamp(3rem,8vw,5rem)] leading-none mt-4 break-words ${result.net>=0?'text-accent':'text-white'}`}>{eur(result.net)}</p><p className="text-sm text-white/65 mt-3">modellierter Nettoeffekt nach den eingetragenen Kosten</p><div className="grid grid-cols-2 gap-5 mt-8 pt-6 border-t border-white/15"><div><p className="text-2xl font-editorial">{num(result.recoverable)} h</p><p className="text-xs text-white/55 mt-1">Kapazität/Jahr</p></div><div><p className="text-2xl font-editorial">{Number.isFinite(result.months)?`${result.months.toFixed(1)} Mon.`:'—'}</p><p className="text-xs text-white/55 mt-1">rechnerischer Break-even</p></div></div></div>
        <div className="brand-card bg-surface p-6"><h2 className="font-editorial text-xl mb-4">Sensitivität</h2><div className="divide-y divide-ink/10">{scenarios.map(s=><div key={s.name} className="grid grid-cols-[1fr_auto] gap-4 py-3"><div><p className="text-sm font-semibold">{s.name}</p><p className="text-xs text-light">{num(s.hours)} h/Jahr</p></div><p className={`font-editorial text-xl ${s.net<0?'text-red-700':''}`}>{eur(s.net)}</p></div>)}</div></div>
        <div className="brand-card bg-[#F3EFEA] p-6 text-sm text-muted leading-relaxed"><h2 className="font-editorial text-xl text-ink mb-3">Rechenweg</h2><p><strong>Bruttowert:</strong> {people} × {hours} Std. × 52 × {share}% × {adoption}% × {eur(rate)} = {eur(result.gross)}</p><p className="mt-2"><strong>Kosten Jahr 1:</strong> {eur(setupCost)} + 12 × {eur(monthlyCost)} = {eur(result.cost)}</p><p className="mt-4 text-xs text-light">Frei werdende Zeit wird nur dann zu wirtschaftlichem Nutzen, wenn sie produktiv eingesetzt oder echte Fremd-/Mehrkosten vermieden werden. Steuern, Finanzierung und Opportunitätskosten sind nicht enthalten.</p></div><Link to="/#kontakt" className="brand-pill justify-center bg-accent text-ink w-full">Szenario mit einem echten Prozess prüfen</Link></section></div>
    <div className="mt-14 pt-8 border-t border-ink/10 max-w-3xl"><p className="text-xs text-muted leading-relaxed"><strong className="text-ink">Datennutzung:</strong> Die Berechnung erfolgt lokal in Ihrem Browser. die Rechnerwerte werden von diesem Tool nicht an die API gesendet.</p></div></div></main>;
};
export default ROICalculator;
